apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-pod
spec:
  containers:
  - name: cpu-stress
    image: vish/stress
    resources:
      limits: "100"
        cpu: "1"
      requests: "100"
        cpu: "0.5"
    args:
    - -cpus
    - "2"
